import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Arcitect Housing Society",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" style={{ fontFamily: "var(--font-nexa)" }}>
        {children}
      </body>
    </html>
  );
}
